#name: Build-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
    - develop
    - master
  paths:
    exclude:
    - .azuredevops/**
    - .github/**

resources:
  repositories:
    - repository: build-tools
      type: git
      name: build-tools

variables:
- group: "YAML - Build"
- group: "Build - Chocolatey"
- group: "Build - Nuget"
- group: "GitHub - BapCabrera"
- template: pipelines/azuredevops/build/variables/common.yml@build-tools

stages: 
- template: pipelines/azuredevops/build/pipepline-psmodule.yml@build-tools
#- stage: TestAndBuild
#  displayName: Test and Build
#  jobs:
#  - template: pipelines/azuredevops/build/jobs/test.yml@build-tools
#    parameters:
#      name: 'TestWindows'
#      pool: '${{ variables.buildPoolName }}'
#      vmImage: '${{ variables.buildPoolWindowsVm }}'
#  - template: pipelines/azuredevops/build/jobs/test.yml@build-tools
#    parameters:
#      name: 'TestLinux'
#      pool: '${{ variables.buildPoolName }}'
#      vmImage: '${{ variables.buildPoolLinuxVm }}'
#  - job: Build
#    displayName: Build Module
#    pool:
#      name: $(BuildPoolName)
#      vmImage: $(BuildPoolWindowsVm)
#    dependsOn:
#      - TestWindows
#      - TestLinux
#    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
 