name: $(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
    - test
  paths:
    exclude:
    - azure-release.yml

variables:
- group: "Build"
- group: "Build - Chocolatey"
- group: "Build - Nuget"
- group: "GitHub - BapCabrera"
- name: 'poolName'
  value: 'Azure Pipelines'
- name: 'poolVmImage'
  value: 'vs2017-win2016'
- name: choco-pack
  value: 'false'
- name: choco-push
  value: 'false'
- name: nuget-pack
  value: 'false'
- name: nuget-push
  value: 'false'

stages: 
- stage: Build
  displayName: Stage Build and Test
  pool:
    name: $(poolName)
    vmImage: $(poolVmImage)
  jobs:
  - job: Build
    displayName: Job Build and Test
    steps:
    - task: CopyFiles@2
      displayName: 'Copy Sources '
      inputs:
        SourceFolder: 'src/$(Build.DefinitionName)'
        Contents: |
          **
          !**\.gitignore
        TargetFolder: '$(BuildSourcesDirectory)'
        CleanTargetFolder: true
        OverWrite: true
    - powershell: |
        Write-Host '$(BuildArtifacts)'
      displayName: 'Test'
    - powershell: |
          Write-Host '$(choco-pack)'
          #Find-Module -Name Bca.Nuget | Install-Module -Scope CurrentUser -Force
      displayName: 'Install Bca.Nuget'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(BuildSourcesDirectory)'
        artifact: '$(Build.DefinitionName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), ne(variables['Build.SourceBranchName'], 'develop'))

- stage: NotMaster
  displayName : Stage Not Master
  pool:
    name: $(poolName)
    vmImage: $(poolVmImage)
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
  - job: NotMaster
    displayName: Job Not Master
    steps:
    - powershell: |
        Write-Host 'Hi'
      displayName: 'Test'

- stage: NotPR
  displayName: Stage not a Pull Request 
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  pool:
    name: $(poolName)
    vmImage: $(poolVmImage)
  jobs: 
  - job: NotPR
    displayName: Job not a Pull Request
    steps:
    - powershell: |
        Write-Host 'Hi'
      displayName: 'Test'

- stage: All
  displayName: Stage Run for all
  pool:
    name: $(poolName)
    vmImage: $(poolVmImage)
  dependsOn: Build
  jobs:
  - job: All
    displayName: Job run for all
    steps:
    - powershell: |
        Write-Host 'Hi'
      displayName: 'Test'