name: Build-$(Date:yyyyMMdd).$(Rev:r)

parameters:
- name: nugetPack
  displayName: Create NuGet Package
  type: boolean
  default: true
- name: nugetPush
  displayName: Publish NuGet Package
  type: boolean
  default: true
- name: chocoPack
  displayName: Create Chocolatey Package
  type: boolean
  default: true
- name: chocoPush
  displayName: Publish Chocolatey Package
  type: boolean
  default: true

trigger:
  branches:
    include:
    - develop
    - master
  paths:
    exclude:
    - .azuredevops/**
    - .github/**

resources:
  repositories:
    - repository: build-tools
      type: git
      name: build-tools

variables:
- template: pipelines/azuredevops/variables/all.yml@build-tools

stages: 
- template: pipelines/azuredevops/pipeline-build-ps.yml@build-tools
  parameters:
    buildName: $(Build.DefinitionName)
    psType: Module
    sourceDirectory: $(Build.Repository.LocalPath)
    nugetPack: ${{ parameters.nugetPack }}
    nugetPush: ${{ parameters.nugetPush }}
    chocoPack: ${{ parameters.chocoPack }}
    chocoPush: ${{ parameters.chocoPush }}