trigger:
- none

variables:
- name: buildName
  value: ${{ replace(variables['Build.DefinitionName'],'.Release','') }}
- name: relName
  value: ${{ replace(variables['Release.DefinitionName'],'Release','') }} 
- name: 'pool.name'
  value: 'Azure Pipelines'
- name: 'pool.vmImage'
  value: 'vs2017-win2016'

resources:
  pipelines:
  - pipeline: Build
    source: ${{ variables['buildName'] }}'
    trigger: 
      branches:
      - test
      - test2

stages:
  - stage: PreRelease
    displayName: PreRelease
    environment: PreRelease
    pool:
      name: $(pool.name)
      vmImage: $(pool.vmImage)
    jobs:
    - deployment: Deploy
      displayName: Deploy It
      strategy:
        runOnce:
          deploy:
            steps:           
            - powershell: |
                Write-Host 'Build.DefinitionName: $(Build.DefinitionName)'
                Write-Host 'Release.DefinitionName: $(Release.DefinitionName)'
                Write-Host 'buildName: $(buildName)'
                Write-Host 'relName: $(relName)'
                Write-Host 'projectID: $(resources.pipeline.Build.projectID)'
                Write-Host 'pipelineName: $(resources.pipeline.Build.pipelineName)'
                Write-Host 'pipelineID: $(resources.pipeline.Build.pipelineID)'
                Write-Host 'runName: $(resources.pipeline.Build.runName)'
                Write-Host 'runID: $(resources.pipeline.Build.runID)'
                Write-Host 'runURI: $(resources.pipeline.Build.runURI)'
                Write-Host 'sourceBranch: $(resources.pipeline.Build.sourceBranch)'
                Write-Host 'sourceCommit: $(resources.pipeline.Build.sourceCommit)'
                Write-Host ':sourceProvider $(resources.pipeline.Build.sourceProvider)'
                Write-Host 'requestedFor: $(resources.pipeline.Build.requestedFor)'
                Write-Host 'requestedForID: $(resources.pipeline.Build.requestedForID)'
              displayName: 'Test'
            - powershell: |
                Get-ChildItem '$(PIPELINE.WORKSPACE)/Build/$(resources.pipeline.Build.pipelineName)-$(resources.pipeline.Build.runName)' -Recurse
              displayName: 'List'
