name: Release-$(Date:yyyyMMdd).$(Rev:r)

parameters:
- name: nugetPub
  displayName: Publish NuGet Package
  type: boolean
  default: true
- name: chocoPub
  displayName: Publish Chocolatey Package
  type: boolean
  default: true
- name: testWindows
  displayName: Test on Windows
  type: boolean
  default: true
- name: testLinux
  displayName: Test on Linux
  type: boolean
  default: true
- name: testMacOs
  displayName: Test on MacOS
  type: boolean
  default: true

trigger:
- none

resources:
  pipelines:
  - pipeline: Build
    source: Build\Bca.Test
    trigger: 
      branches:
      - master
      - develop
      - test
  repositories:
    - repository: build-tools
      type: git
      name: build-tools

variables:
- template: pipelines/azuredevops/variables/all.yml@build-tools
- group: Secrets


stages: 
- stage: test
  jobs:
  - job: test
    steps:
    - powershell: |
        Write-Host 'projectID: $(resources.pipeline.Build.projectID)'
        Write-Host 'pipelineName: $(resources.pipeline.Build.pipelineName)'
        Write-Host 'pipelineID: $(resources.pipeline.Build.pipelineID)'
        Write-Host 'runName: $(resources.pipeline.Build.runName)'
        Write-Host 'runID: $(resources.pipeline.Build.runID)'
        Write-Host 'runURI: $(resources.pipeline.Build.runURI)'
        Write-Host 'sourceBranch: $(resources.pipeline.Build.sourceBranch)'
        Write-Host 'sourceCommit: $(resources.pipeline.Build.sourceCommit)'
        Write-Host ':sourceProvider $(resources.pipeline.Build.sourceProvider)'
        Write-Host 'requestedFor: $(resources.pipeline.Build.requestedFor)'
        Write-Host 'requestedForID: $(resources.pipeline.Build.requestedForID)'
      displayName: 'Test'
    - powershell: |
        Get-ChildItem '$(PIPELINE.WORKSPACE)' -Recurse
      displayName: 'List'
- template: pipelines/azuredevops/pipeline-release-ps.yml@build-tools
  parameters:
    buildName: $(resources.pipeline.Build.pipelineName)
    artifactName: $(resources.pipeline.Build.pipelineName)-$(resources.pipeline.Build.runName)
    psType: Module
    nugetFeed: $[variables.nugetFeedName]
    nugetPub: ${{ parameters.nugetPub }}
    chocoFeed: $[variables.chocoFeedName]
    chocoPub: ${{ parameters.chocoPub }}
    testWindows: ${{ parameters.testWindows }}
    testLinux: ${{ parameters.testLinux }}
    testMacOs: ${{ parameters.testMacOs }}