name: Release-$(Date:yyyyMMdd).$(Rev:r)

parameters:
- name: nugetPub
  displayName: Publish NuGet Package
  type: boolean
  default: true
- name: chocoPub
  displayName: Publish Chocolatey Package
  type: boolean
  default: true
- name: testWindows
  displayName: Test on Windows
  type: boolean
  default: true
- name: testLinux
  displayName: Test on Linux
  type: boolean
  default: true
- name: testMacOs
  displayName: Test on MacOS
  type: boolean
  default: true

trigger:
- none

resources:
  pipelines:
  - pipeline: Build
    source: Build\Bca.Test
    trigger: 
      branches:
      - master
      - develop
      - test
  repositories:
    - repository: build-tools
      type: git
      name: build-tools

variables:
- template: pipelines/azuredevops/variables/all.yml@build-tools
- group: Secrets


stages: 
- stage: test
  jobs:
  - job: test
    steps:
    - powershell: |
        Get-ChildItem '$(PIPELINE.WORKSPACE)/Build/$(resources.pipeline.Build.pipelineName)-$(resources.pipeline.Build.runName)' -Recurse
      displayName: 'List'
#- template: pipelines/azuredevops/pipeline-release-ps.yml@build-tools
#  parameters:
#    buildName: $(resources.pipeline.Build.pipelineName)
#    artifactName: $(resources.pipeline.Build.pipelineName)-$(resources.pipeline.Build.runName)
#    psType: Module
#    nugetFeed: $[variables.nugetFeedName]
#    nugetPub: ${{ parameters.nugetPub }}
#    chocoFeed: $[variables.chocoFeedName]
#    chocoPub: ${{ parameters.chocoPub }}
#    testWindows: ${{ parameters.testWindows }}
#    testLinux: ${{ parameters.testLinux }}
#    testMacOs: ${{ parameters.testMacOs }}