jobs:
- job: Test
  strategy:
    matrix:
      windows:
        poolName: 'Azure Pipelines'
        vmImage: windows-latest
      linux:
        poolName: 'Azure Pipelines'
        vmImage: ubuntu-latest
      macOS:
        poolName: 'Azure Pipelines'
        vmImage: macOS-latest
  pool:
    name: $(poolName)
    vmImage: $(vmImage)
  steps:
  - checkout: none
  - powershell: Write-Host "$(Agent.OS)"