variables:
- name: buildPoolName
  value: 'Azure Pipelines'

jobs:
- job: Test
  strategy:
    matrix:
      windows:
        poolName: $[variables.buildPoolName]
        vmImage: windows-latest
      linux:
        poolName: $[variables.buildPoolName]
        vmImage: ubuntu-latest
      macOS:
        poolName: $[variables.buildPoolName]
        vmImage: macOS-latest
  pool:
    name: $(poolName)
    vmImage: $(vmImage)
  steps:
  - checkout: none
  - powershell: Write-Host "$(Agent.OS)"