name: Sync repo to Azure DevOps 2

on:
  push:
    branches:
    - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror Repo
        uses: spyoungtech/mirror-action@master
        with:
          REMOTE: "https://baptistecabrera@dev.azure.com/baptistecabrera/Bca/_git/bca-test"
          #GIT_USERNAME: "baptiste.cabrera@outlook.com"
          GIT_PASSWORD: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
