name: Sync repo to Azure DevOps

on:
  push:
    branches:
    - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: franzdiebold/github-env-vars-action@v1.1.2
      - uses: actions/checkout@v1
      - name: Mirror Repo
        uses: spyoungtech/mirror-action@v0.3.0
        with:
          REMOTE: "https://dev.azure.com/baptistecabrera/Bca/_git/bca-test"
          GIT_USERNAME: "baptiste.cabrera@outlook.com"
          GIT_PASSWORD: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
