name: Sync repo to Azure DevOps

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: mirror-repository
      uses: spyoungtech/mirror-action@v0.3.0
      with:
        REMOTE: "https://baptistecabrera@dev.azure.com/baptistecabrera/Bca/_git/bca-test.git"
        GIT_PASSWORD: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
